### ISSUE TITLE
关于大文件夹提醒和底栏溢出

### ISSUE THREAD

**Issue by TalexDreamSoul** [qqlittleice/MiuiHome_R#54]
1. 在大文件夹出现提醒时，建议增加修改通知图标位置功能，如图!
![-44219c9f9df1cfd9.jpg](https://user-images.githubusercontent.com/59305952/207659781-39f89b7d-4424-42fe-91b2-797d08c74cb7.jpg)

2. 当选择折叠屏样式时，建议增加自定义最近任务数量功能，不然![Screenshot_2022-12-15-00-59-46-165_com.miui.home-edit.jpg](https://user-images.githubusercontent.com/59305952/207659390-31c67e51-783f-4e97-bba2-6d493d91df3a.jpg)

**Comment by YuKongA** [comment]
自定义应用数量加上了，文件夹这个暂时不打算搞

**Comment by TalexDreamSoul** [comment]
> 自定义应用数量加上了，文件夹这个暂时不打算搞

thanks.
